[package]
name = "yrs"
version = "0.6.0"
description = "High performance implementation of the Yjs CRDT"
license = "MIT"
authors = ["Kevin Jahns <kevin.jahns@pm.me>", "Bartosz Sypytkowski <b.sypytkowski@gmail.com>"]
keywords = ["crdt", "yrs"]
edition = "2018"
homepage = "https://github.com/yjs/yrs/"
repository = "https://github.com/yjs/yrs/"
readme = "./README.md"

[dependencies]
rand = { version = "0.7.0", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"
lib0 = { path = "../lib0", version = "0.6.0"}
smallstr = { version = "0.2", features = ["union"]}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false

[lib]
doctest = true
bench = true
doc = true
